INSERT INTO "category" 
(name, rating) VALUES 
('Herman-Hermann','4'), 
('Koch, Price and Rempel','2'), 
('Kris, Kassulke and Beier','1'), 
('Stroman, Pouros and Lehner','4'), 
('Kling and Sons','4'), 
('Hane, OConner and RoweConner and RoweConner and Rowe','1'), 
('Morar LLC','4'), 
('Koss LLC','2'), 
('Little and Sons','2'), 
('Rodriguez Inc','3'), 
('Cruickshank, Veum and Fisher','4'), 
('Boyer-Bogisich','3'), 
('Kunde, Kihn and Langosh','3'), 
('Streich, Little and Prohaska','4'), 
('Rippin, Turner and Hackett','4'), 
('Purdy-Trantow','4'), 
('Schroeder, Kertzmann and Cruickshank','2'), 
('Trantow, Aufderhar and Cole','3'), 
('McLaughlin-Wilkinson','5'), 
('Schmidt and Sons','3'), 
('Dach Inc','2'), 
('Leannon Group','4'), 
('Walker, Murray and Langosh','5'), 
('Kuhn-Nienow','4'), 
('West, Ferry and Lockman','4'), 
('Koss-Mueller','3'), 
('Lockman LLC','3'), 
('Baumbach, Dietrich and Kerluke','3'), 
('Williamson Group','5'), 
('Hartmann, Walker and Spencer','3')
