INSERT INTO "category" 
(name, rating) VALUES 
('Trantow-Macejkovic','3'), 
('Abbott LLC','1'), 
('Bruen-Brekke','3'), 
('Crooks, Hoeger and Maggio','3'), 
('Hodkiewicz, Watsica and Heidenreich','2'), 
('Vandervort, Rice and Murphy','4'), 
('Hand, Stoltenberg and Beer','5'), 
('Cole Inc','3'), 
('Mayert Inc','4'), 
('Bahringer Inc','3'), 
('Purdy Group','4'), 
('Larson, Lowe and Crist','5'), 
('Ortiz and Sons','3'), 
('Rippin, Brakus and Volkman','5'), 
('Wyman-Graham','2'), 
('Kuhic-Schoen','4'), 
('Davis-Keeling','3'), 
('Donnelly Inc','3'), 
('Parker-MacGyver','4'), 
('OConner LLCConner LLCConner LLC','3')
